### ISSUE TITLE
Option to force use VLC for all files instead of HTML5 player

### ISSUE THREAD

**Issue by MikeSkril** [NDVM/NDVM#18]
Any chance to get that working under Ubuntu 16.04?
I'll get below message when I click on a video thumbnail...

> Service Call failed
> endpoint: "media/play"
> message: "object Object"

Here is the terminal output:

> [INFO] "Wwidd Debug" enabled
> [INFO] no nvm detected! Consider on install it to use the recommended node version.
> ===> Further details please check the nvm page: https://github.com/creationix/nvm
> [INFO] Node.JS version: v4.2.6
> [OK] Executing wwidd ...
> [OK] Node.JS return:
> 
> SYSTEM - OS type: linux
> DB - switching over to DB: default
> DB/default - executing query
> TOOL - executing: sqlite3 -header -line ../db/default.sqlite SELECT value FROM system WHERE key = 'version'
> 'DEBUG' set to true
> TOOL - executing: ifconfig 
> SQLITE - retrieved 0 records.
> DB/default - version: 0.1
> DB/default - executing non-query
> SQLITE - reading SQL command from file: patch.0.2.sql
> TOOL - executing: sqlite3 ../db/default.sqlite ------------------------------
> -- Database patch 0.1 -> 0.2
> ------------------------------
> 
> ------------------------------
> -- Creating sys table
> BEGIN TRANSACTION;
> CREATE TABLE IF NOT EXISTS system(
> 	key TEXT,
> 	value TEXT
> );
> CREATE UNIQUE INDEX IF NOT EXISTS system_id ON system(key ASC);
> INSERT OR REPLACE INTO system (key, value) VALUES ('version', '0.2');
> COMMIT;
> 
> ------------------------------
> -- Creating root ID column
> BEGIN TRANSACTION;
> CREATE TEMPORARY TABLE roots_backup(path);
> INSERT INTO roots_backup SELECT path from roots;
> DROP TABLE roots;
> CREATE TABLE IF NOT EXISTS roots (
> 	rootid INTEGER PRIMARY KEY AUTOINCREMENT,
> 	path TEXT
> );
> CREATE UNIQUE INDEX IF NOT EXISTS roots_id ON roots(path ASC);
> INSERT INTO roots (path) SELECT path from roots_backup;
> DROP TABLE roots_backup;
> COMMIT;
> 
> ------------------------------
> -- Altering table "media"
> BEGIN TRANSACTION;
> CREATE TEMPORARY TABLE media_backup(mediaid, path, rating);
> INSERT INTO media_backup SELECT mediaid, path, rating FROM media;
> DROP TABLE media;
> CREATE TABLE media(
> 	mediaid INTEGER PRIMARY KEY,
> 	rootid INTEGER,			-- NEW
> 	path TEXT,					-- MODIFIED
> 	rating NUMERIC,
> 	hash TEXT,					-- NEW
> 	--thumbnail BLOB		-- REMOVED
> 	FOREIGN KEY(rootid) REFERENCES roots(rootid)
> );
> CREATE UNIQUE INDEX IF NOT EXISTS media_id ON media(path ASC);
> CREATE INDEX IF NOT EXISTS media_rating ON media (rating ASC);
> INSERT INTO media (mediaid, rootid, path, rating)
> 	SELECT mediaid, roots.rootid, substr(media_backup.path, length(roots.path) + 1), rating
> 	FROM media_backup
> 	JOIN roots ON media_backup.path LIKE roots.path || '%';
> DROP TABLE media_backup;
> COMMIT;
> 
> 
> IFCONFIG - no IP detected, using loopback IP
> Server running at http://0.0.0.0:8124
> TOOL - executing: xdg-open http://0.0.0.0:8124
> TOOL - silently failed. Tool 'sqlite3' exited with code: 1.
> SQLITE - query failed
> <Buffer 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 0a 2d 2d 20 44 61 74 61 62 61 73 65 20 70 61 74 63 68 20 30 ... >
> DB/default - patched to version 0.2
> Browser started.
> WALKER - walking path: ../db/
> TOOL - executing: gzip 
> SELECT media.mediaid, hash, roots.path || media.path AS path, rating, tags, keywords FROM media JOIN roots USING (rootid) NATURAL LEFT JOIN ( SELECT mediaid, group_concat(name || ':' || CASE WHEN kind IS NOT NULL THEN kind ELSE '' END) AS tags FROM tags GROUP BY mediaid) NATURAL LEFT JOIN ( SELECT mediaid, group_concat(key || ':' || replace(value, ',', ' ')) AS keywords FROM keywords GROUP BY mediaid) WHERE 1 
> DB/default - executing query
> TOOL - executing: sqlite3 -header -line ../db/default.sqlite SELECT media.mediaid, hash, roots.path || media.path AS path, rating, tags, keywords FROM media JOIN roots USING (rootid) NATURAL LEFT JOIN ( SELECT mediaid, group_concat(name || ':' || CASE WHEN kind IS NOT NULL THEN kind ELSE '' END) AS tags FROM tags GROUP BY mediaid) NATURAL LEFT JOIN ( SELECT mediaid, group_concat(key || ':' || replace(value, ',', ' ')) AS keywords FROM keywords GROUP BY mediaid) WHERE 1 
> SQLITE - retrieved 2 records.
> TOOL - executing: gzip 
> SELECT mediaid, roots.path AS root, media.path AS path, hash FROM media JOIN roots USING (rootid) WHERE mediaid = 2
> DB/default - executing query
> TOOL - executing: sqlite3 -header -line ../db/default.sqlite SELECT mediaid, roots.path AS root, media.path AS path, hash FROM media JOIN roots USING (rootid) WHERE mediaid = 2
> TOOL - executing: gzip 
> SQLITE - retrieved 0 records.
> SELECT roots.rootid, mediaid, roots.path AS root, media.path AS path, hash FROM media JOIN roots USING (rootid) WHERE mediaid IN ('2')
> DB/default - executing query
> TOOL - executing: sqlite3 -header -line ../db/default.sqlite SELECT roots.rootid, mediaid, roots.path AS root, media.path AS path, hash FROM media JOIN roots USING (rootid) WHERE mediaid IN ('2')
> ERROR: TypeError: Cannot read property 'root' of undefined
> ERROR: TypeError: Cannot read property 'root' of undefined
> ERROR: TypeError: Cannot read property 'root' of undefined
> SQLITE - retrieved 1 records.

**Comment by hlechner** [comment]
Hey Mike,

Looking at your messages it seems that you are using **wwidd** instead of **NDVM**, is that right?

Look that part of your logs:
```
[INFO] "Wwidd Debug" enabled
```
```
[OK] Executing wwidd ...
```

NDVM is a fork from wwidd with different code, I have solved some of the issues that your facing on wwidd.

So, please copy a NDVM repo to your computer and give it a try instead of wwidd:
```
git clone https://github.com/NDVM/NDVM.git
```

and let me know how it goes!

**Comment by MikeSkril** [comment]
Stupid me! I have  used the wrong repo! It seems to be working now. I see that the video is played in the browser not opening VLC anymore. Any way to change that?

By the way...thanks for your work! Thats exactly what I was looking for since a long time!

**Comment by hlechner** [comment]
Oh, Long time I don't touch on this code, there is a way I just need remember how.

I will check it and return to you.

**Comment by MikeSkril** [comment]
Your help is much appreciated!

**Comment by MikeSkril** [comment]
I dont know what I've changed but it's opening VLC now. Thanks!

**Comment by hlechner** [comment]
Its because of filetype, some filetypes do not run in html5 due to codecs, in this case it runs on vlc, I will provide some way to force to use vlc on all cases

**Comment by MikeSkril** [comment]
I also saw that thumbnails are not generated for all files. The file extension doesn't seem to be the issue. I see the ffmpeg command in the log but there is no thumbnail created in the 'cache' folder. I will open a new issue with more details. Thanks again!

**Comment by MikeSkril** [comment]
I think I know now why some thumbnails are not created. I had some video examples with less than 15 seconds. I guess `-ss ` is the reason why, right?

```
self.exec = function (inPath, outPath, count, handler) {
		var args = outPath ? [
			'-i', inPath ,
			'-f', 'image2',
			'-vframes', count || 1,
			'-aspect', '4:3',
			'-filter:vf', 'scale=\'if(gt(a,4/3),128,-1)\':' + 
			   '\'if(gt(a,4/3),-1,96)\',' + 
			   'pad=w=128:h=97:x=(ow-iw)/2:y=(oh-ih)/2:color=black',
			'-y',
			'-ss', '15',
			outPath
		] : [
			'-i', inPath
		];
```

**Comment by hlechner** [comment]
Hey Mike, Could you please raise this in a new separate issue?

Due to a different issue itself.
