### ISSUE TITLE
"This library is empty" even with videos on it

### ISSUE THREAD

**Issue by hlechner** [NDVM/NDVM#9]
It doesn't happen always, it's sporadic.
![image](https://cloud.githubusercontent.com/assets/11244067/13382976/c8bbf448-de5f-11e5-911a-429bf979b954.png)

**Comment by MikeSkril** [comment]
I have the same issue. Is there a workaround? Any idea why this is happening?

**Comment by hlechner** [comment]
No workaround at the moment.

Most of the client side is written in async methods instead of sync ones, it could lead of some parts been executed before others, generating unexpected behaviors.

This bug happens more often when the library is big.

**Comment by hlechner** [comment]
I've made some tests to fix a different issue by make requests for each page instead of a big one.

In this case the bug is more evident. the request are made from client and executed on server but it's returning **nothing** instead of the value in database.

**Comment by hlechner** [comment]
Further investigating: it seems that the callback from the command executed is not holding properly the ``code`` return.

When the database is locked or busy it do not receive the respective code but ``0``, showing it as **OK**.
However it was a not OK and it should try again. that's why it showing nothing some times.

on ``server/tools/tool.js`` I reverted the function removing the toolCallback and adding the original wwidd function back and it seems that node.js version v6+ works with that code.

The original function fix some issues however it do not work since node version v0.10.23 (if I do remember right) and start to work again on v6.

I must check how to fix it.

**Comment by hlechner** [comment]
This last commit should fix that.

@MikeSkril Let me know if you still facing this issue.
